[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true

# For static export - SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect old paths
[[redirects]]
  from = "/insurance"
  to = "/contact/"
  status = 301

# Enhanced security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Performance optimization headers
    X-DNS-Prefetch-Control = "on"
    Accept-CH = "DPR, Width, Viewport-Width, Save-Data"
    Critical-CH = "Save-Data"
    
    # Compression and caching directives
    Vary = "Accept-Encoding, Save-Data"
    X-Served-By = "Netlify"
    
    # Service Worker and PWA support
    Service-Worker-Allowed = "/"
    
    # Enhanced preload and prefetch resources
    Link = '''</_next/static/css/275ed64cc4367444.css>; rel=preload; as=style,
              </_next/static/chunks/main-009c5e60c95ecccb.js>; rel=preload; as=script,
              </_next/static/chunks/framework-8e0e0f4a6b83a956.js>; rel=preload; as=script,
              </_next/static/chunks/react-vendor.js>; rel=preload; as=script,
              </manifest.json>; rel=preload; as=fetch; crossorigin,
              </services>; rel=prefetch,
              </assessment>; rel=prefetch,
              </contact>; rel=prefetch,
              </about>; rel=prefetch,
              </testimonials>; rel=prefetch'''

# Optimal caching for different asset types
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Vary = "Accept"
    X-Content-Type-Options = "nosniff"

# Optimized HTML caching with ETag support
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=31536000, must-revalidate"
    Vary = "Accept-Encoding"

# Enhanced CSS caching
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Content-Type = "text/css; charset=utf-8"

# Enhanced JavaScript caching  
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Service Worker caching
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest and PWA files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json; charset=utf-8"

# Image optimization headers
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Vary = "Accept"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Vary = "Accept"

# API response caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Advanced compression settings
[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "br, gzip"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"

# Brotli compression for specific file types
[[headers]]
  for = "*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript; charset=utf-8"

# WebP and AVIF optimization
[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept"
    Access-Control-Allow-Origin = "*"

# Critical CSS caching
[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"
    X-Content-Type-Options = "nosniff"